export const FLOAT32_BYTES = 4;
export const WEB_AUDIO_BLOCK_SIZE = 128;
export const SUSTAINED_BUFFERED_AUDIO_SECONDS = 2.5;
export const SCHEDULE_AHEAD_RATIO = 0.75;
export const TARGET_BUFFER_LENGTH_SECONDS = 0.4;
export const SUSTAINED_BUFFER_COUNT = Math.ceil(SUSTAINED_BUFFERED_AUDIO_SECONDS / TARGET_BUFFER_LENGTH_SECONDS);
export const MIN_BUFFERS_TO_REQUEST = Math.ceil(SUSTAINED_BUFFER_COUNT / 4);
