packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  fast-json-stringify@*:
    dependencies:
      long: "*"
  pino@*:
    dependencies:
      pino-pretty: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-sources.cjs
