version: '3'
services:
  html_music_player_dev:
    build:
      context: .
      dockerfile: Dockerfile.development
    user: node
    environment:
    - NODE_ENV=development
    - SERVER_PORT=8139
    ports:
    - "8140:8140"
    volumes:
    - ./dist:/opt/web/
    - ./backend/dist:/opt/server/
    working_dir: /opt/server
    command: bash -c "nginx && node-dev index.js"
