#!/usr/bin/env python

import BaseHTTPServer, SimpleHTTPServer
import ssl

print "Server will run at https://localhost:4443"
httpd = BaseHTTPServer.HTTPServer(('0.0.0.0', 4443), SimpleHTTPServer.SimpleHTTPRequestHandler)
httpd.socket = ssl.wrap_socket (httpd.socket, certfile='./server.pem', server_side=True)
httpd.serve_forever()
