export const {ArrayBuffer,
    Blob,
    File,
    Int8Array,
    Uint8Array,
    Uint8ClampedArray,
    Int16Array,
    Uint16Array,
    Int32Array,
    Uint32Array,
    Float32Array,
    Float64Array,
    AudioContext,
    URL,
    FileReader,
    DataView,
    MouseEvent,
    EventEmitter,
    Worker,
    indexedDB,
    IDBKeyRange,
    Directory,
    Image,
    codecLoaded,
    XMLHttpRequest,
    performance,
    console,
    MediaError,
    MediaMetadata,
    AudioParam,
    matchMedia,
    Symbol,
    TextDecoder,
    TextEncoder,
    crypto,
    Map,
    FileReaderSync,
    importScripts,
    MessageChannel,
    fetch,
    Request,
    Response,
    Proxy,
    WebAssembly
} = self;

const global = self;

export {global as self};
